### ISSUE TITLE
ImportError: No module named 'httplib2'

### ISSUE THREAD

**Issue by Arinerron** [aaronshaver/coinbase-google-sheets#1]
I have `httplib2` installed, but it doesn't seem to recognise that. Any ideas?

```
➜  coinbase-google-sheets git:(master) sudo apt-get install python3-httplib2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-httplib2 is already the newest version.
The following packages were automatically installed and are no longer required:
  libecj-java libjetty8-java libsoapysdr0.5-2 libwireshark3 libwiretap3
  libwsutil3
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
➜  coinbase-google-sheets git:(master) pip install httplib2      
Requirement already satisfied: httplib2 in /usr/lib/python3/dist-packages
➜  coinbase-google-sheets git:(master) python3 app.py --sheet-id=[snipped]
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import httplib2
ImportError: No module named 'httplib2'
```

**Comment by Arinerron** [comment]
Here's another snippet:

```
➜  coinbase-google-sheets git:(master) python3 app.py --sheet_id=[snip]
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import httplib2
ImportError: No module named 'httplib2'
➜  coinbase-google-sheets git:(master) sudo pip install httplib2
The directory '/home/aaron/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/aaron/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: httplib2 in /usr/lib/python3/dist-packages
➜  coinbase-google-sheets git:(master) python3 app.py --sheet_id=[snip]
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import httplib2
ImportError: No module named 'httplib2'
```

**Comment by aaronshaver** [comment]
I know for sure it works on Mac OS X w/Python 3. What does `pip list | grep http` (or maybe pip3) show for you? On my Mac it's `httplib2 (0.10.3)`

What's weird is when I run it with `python` (which does 2.7.10 on my Mac), I get your `No module named httplib2 error`.

Can you make sure you're using Python 3? Maybe python3 is aliased to something different. When you do `python3 --version` does it show something close to `Python 3.6.1`?

**Comment by Arinerron** [comment]
@aaronshaver Thanks for the response! The output for the pip command was:

```
➜  pip list | grep http
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
httplib2 (0.8)
```

Both `pip3` and `pip` had the same output.

and for python3:

```
➜  python3 --version
Python 3.4.2
```

**Comment by aaronshaver** [comment]
How about pip3 list ?

**Comment by Arinerron** [comment]
Both pip3 and pip had the same output.

**Comment by aaronshaver** [comment]
Weird. I'm at a loss. For giggles can you try running the app with Python 2?

**Comment by Arinerron** [comment]
@aaronshaver Okay, this is getting weirder and weirder.

```
➜  crypto-currency-portfolio git:(master) sudo pip3 install flask
The directory '/home/aaron/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/aaron/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: flask in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python3.4/dist-packages (from flask)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.4/dist-packages (from flask)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python3.4/dist-packages (from flask)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python3.4/dist-packages (from flask)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.4/dist-packages (from Jinja2>=2.4->flask)

➜  crypto-currency-portfolio git:(master) python app.py          
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from flask import Flask
ImportError: No module named flask

➜  crypto-currency-portfolio git:(master) python --version       
Python 2.7.6

```

**Comment by aaronshaver** [comment]
Looks like it might be where the modules are installing. Check out this thread and see if your modules are installed in sys.path

https://stackoverflow.com/questions/25119298/importerror-no-modules-named-but-modules-already-installed-in-dist-packages

**Comment by Arinerron** [comment]
@aaronshaver Alright, I fixed that. Now httplib2 and zlib aren't the problems anymore. No matter if I use `python3` or `python`, I always get:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

Double-checked, and flask is installed.

**Comment by Arinerron** [comment]
@aaronshaver After reconfiguring and recompiling twice, there are finally no more import errors. One more problem, though:

```
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    @app.route('/coins/ETH-USD/sell', methods=['GET'])
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1013, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 984, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: coins
```

**Comment by aaronshaver** [comment]
Closing this issue. Can you please open a new one for the new issue?

**Comment by Arinerron** [comment]
@aaronshaver The latest commits fixed it, thanks. Have a great day!

**Comment by aaronshaver** [comment]
Cool. Thanks for your persistence in getting it working. By the way, I am at home now and got it working on my Ubutnu Linux VM. Weirdly while python fails on Mac and python3 works, it's just the opposite on my Linux box.

**Comment by Arinerron** [comment]
@aaronshaver I'd rather not open a new issue for this quick question, so if you don't mind, I'm just going to ask it here: Is the script supposed to output anything? When I run it, there are no errors, no output, and nothing is updated on google sheets.

**Comment by aaronshaver** [comment]
It should, yes. I believe it outputs a timestamp and the latest sell price. Make sure you have your .json file with the OAuth credential stuff in the current dir and that you have the right sheet id and a valid cells range...

**Comment by aaronshaver** [comment]
Oh and make sure you accept the OAuth screen that pops up in a browser... "authroize the coin app to access your stuff" etc

**Comment by Arinerron** [comment]
Okay, got the .json file and put it in the working dir. Do I need to configure the script so it knows where to look for the file? Sheet ID is correct, and the cell range is valid (the default cell range. It is valid).

There was no OAuth browser popup screen. When I run `python3 app.py --sheet-id=[id here]`, it just exits (status `0`) and doesn't print anything.

**Comment by aaronshaver** [comment]
I would go through the Google guide on setting up the sheets API stuff that
I link to in the Readme. You must be missing something from there. It'll
never work if that OAuth piece isn't showing up.
